name: Deploy Web to Ferozo

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy Web App to Ferozo
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Install Node dependencies and Build Assets
        run: |
          npm ci
          npm run build

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: 🎼 Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 🚀 Sync Private Laravel Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /web_laravel/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/public/**
            .env

      - name: 🌐 Sync Public Assets via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /public_html/
